export { ActionSchema, type Action, type ActionInput } from './action.ts'
export { applySurfacePatch, applySurfacePatchEvent } from './apply-patch.ts'
export {
  AuthDeviceSchema,
  AuthModeSchema,
  AuthSessionSchema,
  AuthSessionTokenSchema,
  AuthStatusSchema,
  OneTimeCodeSchema,
  PairingCodeSchema,
  WebAuthnOptionsEnvelopeSchema,
  type AuthDevice,
  type AuthMode,
  type AuthSession,
  type AuthStatus,
  type PairingCode,
  type WebAuthnOptionsEnvelope,
} from './auth.ts'
export {
  atomTypes,
  AtomTypeSchema,
  AtomNodeSchema,
  pendingSlotVariants,
  PendingSlotVariantSchema,
  PendingAtomPropsSchema,
  MIN_PENDING_SLOT_TIMEOUT_MS,
  DEFAULT_PENDING_SLOT_TIMEOUT_MS,
  MAX_PENDING_SLOT_TIMEOUT_MS,
  type AtomType,
  type AtomNode,
  type PendingSlotVariant,
  type PendingAtomProps,
} from './atom.ts'
export {
  SurfaceSchema,
  FreshnessSchema,
  RelativeTimeValiditySchema,
  RelativeTimeWindowSchema,
  SurfaceValidationError,
  parseSurface,
  formatSurfaceIssues,
  collectNodeBindingRefs,
  surfaceRelativeTimeStatus,
  type Surface,
  type Freshness,
  type RelativeTimeValidity,
  type RelativeTimeWindow,
  type SurfaceRelativeTimeStatus,
  type NodeBindingRef,
} from './surface.ts'
export { SpaceSchema, type Space } from './space.ts'
export {
  PendingDecisionKindSchema,
  PendingDecisionResolutionSchema,
  PendingDecisionStateSchema,
  PendingDecisionOutcomeSchema,
  PendingDecisionScopeSchema,
  PendingDecisionSchema,
  PendingDecisionListSchema,
  PendingDecisionResolveRequestSchema,
  PendingDecisionResolveResultSchema,
  formatPendingDecisionId,
  parsePendingDecisionId,
  pendingDecisionNativeId,
  type PendingDecisionKind,
  type PendingDecisionResolution,
  type PendingDecisionState,
  type PendingDecisionOutcome,
  type PendingDecisionScope,
  type PendingDecision,
  type PendingDecisionList,
  type PendingDecisionResolveRequest,
  type PendingDecisionResolveResult,
  type ParsedPendingDecisionId,
} from './pending-decision.ts'
export {
  PatchSchema,
  PatchOperationSchema,
  ActionInvocationSchema,
  type Patch,
  type PatchOperation,
  type ActionInvocation,
} from './patch.ts'
export {
  JsonValueSchema,
  JsonObjectSchema,
  type JsonPrimitive,
  type JsonValue,
  type JsonObject,
} from './json.ts'
export {
  ChatResultTargetSchema,
  ChatMessageSchema,
  ChatClientMessageSchema,
  type ChatResultTarget,
  type ChatMessage,
  type ChatClientMessage,
} from './chat.ts'
export {
  GatewayCursorSchema,
  SurfaceOrderSchema,
  SurfaceMoveDirectionSchema,
  MoveSurfaceRequestSchema,
  MoveSurfaceResultSchema,
  PinSurfaceResultSchema,
  SpaceWithSurfacesSchema,
  SurfaceSnapshotSchema,
  SurfacePatchEventSchema,
  SurfaceCreatedEventSchema,
  SurfaceArchivedEventSchema,
  SurfacePinnedEventSchema,
  SurfaceMovedEventSchema,
  ChatTurnCorrelationSchema,
  ChatTurnStartMessageSchema,
  ChatTurnDeltaMessageSchema,
  ChatTurnEndMessageSchema,
  ChatTurnErrorMessageSchema,
  PresenceStatusSchema,
  PresenceEntrySchema,
  ApprovalCardSchema,
  GatewayClientMessageSchema,
  GatewayServerMessageSchema,
  type GatewayCursor,
  type SurfaceOrder,
  type SurfaceMoveDirection,
  type MoveSurfaceRequest,
  type MoveSurfaceResult,
  type PinSurfaceResult,
  type SpaceWithSurfaces,
  type SurfaceSnapshot,
  type SurfacePatchEvent,
  type SurfaceCreatedEvent,
  type SurfaceArchivedEvent,
  type SurfacePinnedEvent,
  type SurfaceMovedEvent,
  type ChatTurnCorrelation,
  type ChatTurnStartMessage,
  type ChatTurnDeltaMessage,
  type ChatTurnEndMessage,
  type ChatTurnErrorMessage,
  type PresenceStatus,
  type PresenceEntry,
  type ApprovalCard,
  type GatewayClientMessage,
  type GatewayServerMessage,
} from './gateway.ts'
export {
  findAtom,
  findDeclaredAction,
  findDeclaredFastAction,
  findDeclaredAgentAction,
} from './tree.ts'
export {
  PushSubscriptionSchema,
  PushPayloadSchema,
  type PushSubscription,
  type PushPayload,
} from './notification.ts'
// Onboarding wizard protocol (issue 019): step ids/status, installer JSON stage
// protocol, legacy detection, and every request/response schema for
// `/api/onboarding/*` (see `issues/019-onboarding-wizard.md` and
// `docs/references/04-onboarding-migration.md`).
export {
  OnboardingStepIdSchema,
  OnboardingStepStatusSchema,
  OnboardingProfileSchema,
  InstallerStageStatusSchema,
  InstallerStageSchema,
  InstallerStageEventSchema,
  LegacyDetectionSchema,
  ByokProviderSchema,
  OnboardingStatusSchema,
  MigrationChoiceRequestSchema,
  ModelConnectionStepRequestSchema,
  FirstSpaceRequestSchema,
  GmailIntegrationRequestSchema,
  CalendarIntegrationRequestSchema,
  IntegrationsApplyRequestSchema,
  FinishResponseSchema,
  type OnboardingStepId,
  type OnboardingStepStatus,
  type OnboardingProfile,
  type InstallerStageStatus,
  type InstallerStage,
  type InstallerStageEvent,
  type LegacyDetection,
  type ByokProvider,
  type OnboardingStatus,
  type MigrationChoiceRequest,
  type ModelConnectionStepRequest,
  type FirstSpaceRequest,
  type GmailIntegrationRequest,
  type CalendarIntegrationRequest,
  type CalendarIntegrationRequestInput,
  type IntegrationsApplyRequest,
  type FinishResponse,
} from './onboarding.ts'
// Importer wire protocol (issue 020): plan/result schemas shared by the CLI's
// text preview and the wizard's rendered preview, and the two
// `/api/onboarding/migration/*` request/response bodies (see
// `docs/adr/0010-importer-trust-and-refusal.md`).
export {
  ImportSourceKindSchema,
  ImportActionSchema,
  ImportItemSchema,
  ImportOptionsSchema,
  ImportPlanSchema,
  ImportFactCountsSchema,
  ImportResultSchema,
  ImportPreviewRequestSchema,
  ImportApplyRequestSchema,
  ImportApplyResponseSchema,
  type ImportSourceKind,
  type ImportAction,
  type ImportItem,
  type ImportOptions,
  type ImportOptionsInput,
  type ImportPlan,
  type ImportFactCounts,
  type ImportResult,
  type ImportPreviewRequest,
  type ImportPreviewRequestInput,
  type ImportApplyRequest,
  type ImportApplyRequestInput,
  type ImportApplyResponse,
} from './import.ts'
// Emergent Templates (issue 022): a saved Surface composition — tree plus the
// *names* of the state keys it binds, never the typed data — and the portable
// bundle format used to export/import a Space's Templates (see
// `docs/adr/0003-declarative-atoms.md`).
export {
  SurfaceTemplateIdSchema,
  SurfaceTemplateSchema,
  TemplateBundleSchema,
  type SurfaceTemplate,
  type TemplateBundle,
} from './template.ts'
// Model connections (issue #47, `docs/adr/0014-subscription-inference-boundary.md`):
// the connection lifecycle, catalog and device-code shapes, and every
// request/response schema for `/api/model-connections/*`.
export {
  ConnectionLifecycleStateSchema,
  ModelConnectionMethodIdSchema,
  ModelConnectionIdSchema,
  ModelCatalogEntrySchema,
  DeviceChallengeSchema,
  ModelConnectionCapabilitiesSchema,
  ModelConnectionMethodSchema,
  ModelConnectionSchema,
  ModelConnectionSelectionSchema,
  ModelConnectionsSnapshotSchema,
  CreateModelConnectionRequestSchema,
  AuthorizeModelConnectionRequestSchema,
  AuthorizeModelConnectionResponseSchema,
  UpdateModelConnectionRequestSchema,
  VerifyModelConnectionRequestSchema,
  VerifyModelConnectionResponseSchema,
  ApplyModelSelectionRequestSchema,
  ModelConnectionCatalogResponseSchema,
  MockProviderControlRequestSchema,
  type ConnectionLifecycleState,
  type ModelConnectionMethodId,
  type ModelConnectionId,
  type ModelCatalogEntry,
  type DeviceChallenge,
  type ModelConnectionCapabilities,
  type ModelConnectionMethod,
  type ModelConnection,
  type ModelConnectionSelection,
  type ModelConnectionsSnapshot,
  type CreateModelConnectionRequest,
  type AuthorizeModelConnectionRequest,
  type AuthorizeModelConnectionResponse,
  type UpdateModelConnectionRequest,
  type VerifyModelConnectionRequest,
  type VerifyModelConnectionResponse,
  type ApplyModelSelectionRequest,
  type ModelConnectionCatalogResponse,
  type MockProviderControlRequest,
} from './model-connection.ts'
// Signed self-update (issue #43, `docs/adr/0013-signed-self-update.md`): the
// gated feed manifest, the root-owned pinning file, the apply-time marker,
// the transaction's terminal result, and post-hoc progress reporting.
export {
  ReleaseMetadataSchema,
  SigningKeyCertSchema,
  UpdateManifestSchema,
  UpdatePinningSchema,
  UpdateMarkerSchema,
  UpdateResultSchema,
  UpdateStageStatusSchema,
  UpdateStageSchema,
  UpdateProgressSchema,
  type ReleaseMetadata,
  type SigningKeyCert,
  type UpdateManifest,
  type UpdatePinning,
  type UpdateMarker,
  type UpdateResult,
  type UpdateStageStatus,
  type UpdateStage,
  type UpdateProgress,
} from './update.ts'
export { canonicalJson, isJsonValue } from './json.ts'
